wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.50.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1779473378.0
    t:
      1:
      - 1
      - 9
      - 11
      - 33
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 33
      - 41
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.9
      5: 0.16.5
      6: 4.50.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
vision_encoder:
  desc: null
  value: null
text_encoder:
  desc: null
  value: null
args/logger:
  desc: null
  value: true
args/checkpoint_callback:
  desc: null
  value: None
args/enable_checkpointing:
  desc: null
  value: true
args/default_root_dir:
  desc: null
  value: None
args/gradient_clip_val:
  desc: null
  value: None
args/gradient_clip_algorithm:
  desc: null
  value: None
args/process_position:
  desc: null
  value: 0
args/num_nodes:
  desc: null
  value: 1
args/num_processes:
  desc: null
  value: None
args/devices:
  desc: null
  value: None
args/gpus:
  desc: null
  value: 1
args/auto_select_gpus:
  desc: null
  value: false
args/tpu_cores:
  desc: null
  value: None
args/ipus:
  desc: null
  value: None
args/log_gpu_memory:
  desc: null
  value: None
args/progress_bar_refresh_rate:
  desc: null
  value: None
args/enable_progress_bar:
  desc: null
  value: true
args/overfit_batches:
  desc: null
  value: 0.0
args/track_grad_norm:
  desc: null
  value: -1
args/check_val_every_n_epoch:
  desc: null
  value: 5000
args/fast_dev_run:
  desc: null
  value: false
args/accumulate_grad_batches:
  desc: null
  value: None
args/max_epochs:
  desc: null
  value: 20
args/min_epochs:
  desc: null
  value: None
args/max_steps:
  desc: null
  value: -1
args/min_steps:
  desc: null
  value: None
args/max_time:
  desc: null
  value: None
args/limit_train_batches:
  desc: null
  value: None
args/limit_val_batches:
  desc: null
  value: None
args/limit_test_batches:
  desc: null
  value: None
args/limit_predict_batches:
  desc: null
  value: None
args/val_check_interval:
  desc: null
  value: None
args/flush_logs_every_n_steps:
  desc: null
  value: None
args/log_every_n_steps:
  desc: null
  value: 50
args/accelerator:
  desc: null
  value: None
args/strategy:
  desc: null
  value: ddp
args/sync_batchnorm:
  desc: null
  value: false
args/precision:
  desc: null
  value: 32
args/enable_model_summary:
  desc: null
  value: true
args/weights_summary:
  desc: null
  value: top
args/weights_save_path:
  desc: null
  value: None
args/num_sanity_val_steps:
  desc: null
  value: 2
args/resume_from_checkpoint:
  desc: null
  value: None
args/profiler:
  desc: null
  value: None
args/benchmark:
  desc: null
  value: None
args/deterministic:
  desc: null
  value: false
args/reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
args/auto_lr_find:
  desc: null
  value: false
args/replace_sampler_ddp:
  desc: null
  value: true
args/detect_anomaly:
  desc: null
  value: false
args/auto_scale_batch_size:
  desc: null
  value: false
args/prepare_data_per_node:
  desc: null
  value: None
args/plugins:
  desc: null
  value: None
args/amp_backend:
  desc: null
  value: native
args/amp_level:
  desc: null
  value: None
args/move_metrics_to_cpu:
  desc: null
  value: false
args/multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
args/stochastic_weight_avg:
  desc: null
  value: false
args/terminate_on_nan:
  desc: null
  value: None
args/batch_size:
  desc: null
  value: 64
args/drop_last:
  desc: null
  value: true
args/val_batch_size:
  desc: null
  value: 16
args/num_workers:
  desc: null
  value: 8
args/augment_frames:
  desc: null
  value: true
args/eval_include_sos_eos:
  desc: null
  value: true
args/test_while_val:
  desc: null
  value: false
args/eval_type:
  desc: null
  value: image
args/eval_metadata_filename:
  desc: null
  value: eval_filtered_dev.json
args/clip_eval:
  desc: null
  value: false
args/multiple_frames:
  desc: null
  value: false
args/shuffle_utterances:
  desc: null
  value: false
args/pretrained_cnn:
  desc: null
  value: false
args/cnn_model:
  desc: null
  value: models/TC-S-resnext.tar
args/cnn_dino:
  desc: null
  value: false
args/vit_dino:
  desc: null
  value: true
args/finetune_cnn:
  desc: null
  value: true
args/text_encoder:
  desc: null
  value: embedding
args/captioning:
  desc: null
  value: false
args/attention:
  desc: null
  value: false
args/attention_activation:
  desc: null
  value: relu
args/attention_gate:
  desc: null
  value: false
args/crange:
  desc: null
  value: 1
args/dropout_i:
  desc: null
  value: 0.5
args/dropout_o:
  desc: null
  value: 0.0
args/pos_embed_type:
  desc: null
  value: no_pos_embed
args/loadsmallerfirst:
  desc: null
  value: false
args/embedding_type:
  desc: null
  value: flat
args/embedding_dim:
  desc: null
  value: 512
args/normalize_features:
  desc: null
  value: true
args/sim:
  desc: null
  value: max
args/temperature:
  desc: null
  value: 0.07
args/fix_temperature:
  desc: null
  value: true
args/tie:
  desc: null
  value: true
args/bias:
  desc: null
  value: true
args/optimizer:
  desc: null
  value: AdamW
args/lr:
  desc: null
  value: 0.0001
args/lr_scheduler:
  desc: null
  value: true
args/factor:
  desc: null
  value: 0.1
args/patience:
  desc: null
  value: 20
args/weight_decay:
  desc: null
  value: 0.1
args/lambda_mm:
  desc: null
  value: 1.0
args/lambda_lm:
  desc: null
  value: 0.0
args/lambda_ar:
  desc: null
  value: 0.0
args/optimize_unused:
  desc: null
  value: true
args/eval_textgen:
  desc: null
  value: false
args/beam_width:
  desc: null
  value: 3
args/decode_length:
  desc: null
  value: 25
args/length_penalty_alpha:
  desc: null
  value: 0.0
args/lambda_touch:
  desc: null
  value: 1.0
args/num_touch_classes:
  desc: null
  value: 1024
args/exp_name:
  desc: null
  value: vit_speech_only_2
args/triplet:
  desc: null
  value: false
args/seed:
  desc: null
  value: 0
args/resume_ckpt:
  desc: null
  value: None
args/pretrained_ckpt:
  desc: null
  value: models/vit_speech_only.ckpt
args/train_data_path:
  desc: null
  value: data/jsons/full_merged.json
args/dino_ckpt:
  desc: null
  value: None
args/checkpoint_dir:
  desc: null
  value: None
